#!/system/bin/sh
# Readahead optimisation
# TODO: Add dynamic readahead
# TODO: Add a find loop to detect space in bytes and calculate values from there (aka dynamic readahead)

mount -o remount,rw -t auto /
mount -t rootfs -o remount,rw rootfs
mount -o remount,rw -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache

LOG=/data/intelliboost/logs/sdcard.log

# Loop to reset log values
if [ -f \$LOG ]; then
busybox rm \$LOG;
touch \$LOG;
else
	touch \$LOG;
fi;

#Date and Time in enoch format
echo "$( date +"%m-%d-%Y %H:%M:%S" ) Applying I/O tweaks" | tee -a $LOG;
echo "SD Card read_speed also tweaked here" | tee -a $LOG;
echo "Readahead kb optimised for 32gb devices" | tee -a $LOG

#Optimising Readahead KB 
#setvar
readahead_kb="512"

if [ -e /sys/devices/virtual/bdi/0:18/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/0:18/readahead_kb
    echo "SD card read ahead kb SET to $readahead_kb --SUCCESS1!"| tee -a $LOG
fi

if [ -e /sys/devices/virtual/bdi/179:0/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/179:0/readahead_kb
    echo "SD card read ahead kb SET to $readahead_kb --SUCCESS2!"| tee -a $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:0/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:0/readahead_kb
    echo "SD card read ahead kb SET to $readahead_kb --SUCCESS3!"| tee -a $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:1/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:1/readahead_kb
    echo "SD card read ahead kb SET to $readahead_kb --SUCCESS4!"| tee -a $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:2/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:2/readahead_kb
    echo "SD card read ahead kb SET to $readahead_kb --SUCCESS5!"| tee -a $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:3/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:3/readahead_kb
    echo "SD card read ahead kb SET to $readahead_kb --SUCCESS6!"| tee -a $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:4/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:4/readahead_kb
    echo "SD card read ahead kb SET to $readahead_kb --SUCCESS7!"| tee -a $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:5/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:5/readahead_kb
    echo "SD card read ahead kb SET to $readahead_kb --SUCCESS8!"| tee -a $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:6/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:6/readahead_kb
    echo "SD card read ahead kb SET to $readahead_kb --SUCCESS9!"| tee -a $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:7/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:7/readahead_kb
    echo "SD card read ahead kb SET to $readahead_kb --SUCCESS10!"| tee -a $LOG
fi

if [ -e /sys/devices/virtual/bdi/default/readahead_kb ]; then
    echo "256" > /sys/devices/virtual/bdi/default/readahead_kb
    echo "SD card read ahead kb SET to 256 --SUCCESS11(default)!"| tee -a $LOG
fi

    echo "SD card read ahead kb successfully set to $readahead_kb, and default 256" | tee -a $LOG

echo "" | tee -a $LOG
echo "$( date +"%m-%d-%Y %H:%M:%S" ) I/O tweaks applied!" | tee -a $LOG;

mount -o remount,ro -t auto /
mount -t rootfs -o remount,ro rootfs
mount -o remount,ro -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache