#!/system/bin/sh
# Fstrim on boot script

mount -o remount,rw -t auto /
mount -t rootfs -o remount,rw rootfs
mount -o remount,rw -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache

# LOG
LOG=/data/intelliboost/fstrim.log

# Loop to reset log values
if [ -f \$LOG ]; then
busybox rm \$LOG;
touch \$LOG;
else
	touch \$LOG;
fi;

# Fstrim binary (busybox applet)
# Current time is in enoch format

if [ -e /system/bin/fstrim ] || [ -e /system/xbin/fstrim ] || [ -e /sbin/fstrim ];
then
	echo "================================================" | tee -a $LOG
	echo " Fstrim Start at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG
	echo "================================================" | tee -a $LOG

	busybox fstrim -v /system | tee -a $LOG;
	busybox fstrim -v /data | tee -a $LOG;
	busybox fstrim -v /cache | tee -a $LOG;

	echo "================================================" | tee -a $LOG
	echo " Fstrim Done at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG
	echo "================================================" | tee -a $LOG
else
	echo "* Fstrim can't run without Busybox, Please install busybox (playstore) !" | tee -a $LOG
fi

mount -o remount,ro -t auto /
mount -t rootfs -o remount,ro rootfs
mount -o remount,ro -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache