#!/system/bin/sh
# Readahead optimisation
# TODO: Add dynamic readahead
# TODO: Add a find loop to detect space in bytes and calculate values from there (aka dynamic readahead)

LOG=/data/intelliboost/logs/sdcard.log
box=/system/xbin/busybox

# Loop to reset log values
if [ -f \$LOG ]; then
$box rm -f \$LOG;
touch \$LOG;
else
  touch \$LOG;
fi;

mount -o remount,rw -t auto / >> $LOG 2>> $LOG
mount -t rootfs -o remount,rw rootfs >> $LOG 2>> $LOG
mount -o remount,rw -t auto /system >> $LOG 2>> $LOG
mount -o remount,rw /data >> $LOG 2>> $LOG
mount -o remount,rw /cache >> $LOG 2>> $LOG

#Date and Time in enoch format
$box echo "$( date +"%m-%d-%Y %H:%M:%S" ) Applying I/O tweaks" >> $LOG
$box echo "SD Card read_speed also tweaked here" >> $LOG
$box echo "Readahead kb optimised for 32gb devices"  >> $LOG

#Optimising Readahead KB 
#setvar
readahead_kb="512"

if [ -e /sys/devices/virtual/bdi/0:18/readahead_kb ]; then
    $box echo $readahead_kb > /sys/devices/virtual/bdi/0:18/readahead_kb
    $box echo "SD card read ahead kb SET to $readahead_kb --SUCCESS1!" >> $LOG
fi

if [ -e /sys/devices/virtual/bdi/179:0/readahead_kb ]; then
    $box echo $readahead_kb > /sys/devices/virtual/bdi/179:0/readahead_kb
    $box echo "SD card read ahead kb SET to $readahead_kb --SUCCESS2!" >> $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:0/readahead_kb ]; then
    $box echo $readahead_kb > /sys/devices/virtual/bdi/7:0/readahead_kb
    $box echo "SD card read ahead kb SET to $readahead_kb --SUCCESS3!" >> $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:1/readahead_kb ]; then
    $box echo $readahead_kb > /sys/devices/virtual/bdi/7:1/readahead_kb
    $box echo "SD card read ahead kb SET to $readahead_kb --SUCCESS4!" >> $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:2/readahead_kb ]; then
    $box echo $readahead_kb > /sys/devices/virtual/bdi/7:2/readahead_kb
    $box echo "SD card read ahead kb SET to $readahead_kb --SUCCESS5!" >> $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:3/readahead_kb ]; then
    $box echo $readahead_kb > /sys/devices/virtual/bdi/7:3/readahead_kb
    $box echo "SD card read ahead kb SET to $readahead_kb --SUCCESS6!" >> $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:4/readahead_kb ]; then
    $box echo $readahead_kb > /sys/devices/virtual/bdi/7:4/readahead_kb
    $box echo "SD card read ahead kb SET to $readahead_kb --SUCCESS7!" >> $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:5/readahead_kb ]; then
    $box echo $readahead_kb > /sys/devices/virtual/bdi/7:5/readahead_kb
    $box echo "SD card read ahead kb SET to $readahead_kb --SUCCESS8!" >> $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:6/readahead_kb ]; then
    $box echo $readahead_kb > /sys/devices/virtual/bdi/7:6/readahead_kb
    $box echo "SD card read ahead kb SET to $readahead_kb --SUCCESS9!" >> $LOG
fi

if [ -e /sys/devices/virtual/bdi/7:7/readahead_kb ]; then
    $box echo $readahead_kb > /sys/devices/virtual/bdi/7:7/readahead_kb
    $box echo "SD card read ahead kb SET to $readahead_kb --SUCCESS10!" >> $LOG
fi

if [ -e /sys/devices/virtual/bdi/default/readahead_kb ]; then
    $box echo "256" > /sys/devices/virtual/bdi/default/readahead_kb
    $box echo "SD card read ahead kb SET to 256 --SUCCESS11(default)!" >> $LOG
fi

    $box echo "SD card read ahead kb successfully set to $readahead_kb, and default 256"  >> $LOG

$box echo ""  >> $LOG
$box echo "$( date +"%m-%d-%Y %H:%M:%S" ) I/O tweaks applied!" >> $LOG

mount -o remount,ro -t auto / >> $LOG 2>> $LOG
mount -t rootfs -o remount,ro rootfs >> $LOG 2>> $LOG
mount -o remount,ro -t auto /system >> $LOG 2>> $LOG
mount -o remount,rw /data >> $LOG 2>> $LOG
mount -o remount,rw /cache >> $LOG 2>> $LOG