#!/system/bin/sh
# Loop optimising space use (why am i doing this lmao)

# Set Variables
    LOG=/data/intelliboost/logs/loop.log
	count=/data/intelliboost/loop
	zap=`cat $count`
	box=/system/xbin/busybox

# Loop to reset log values
if [ -f \$LOG ]; then
$box rm -f \$LOG;
$box touch \$LOG;
else
  $box touch \$LOG;
fi;

mount -o remount,rw -t auto / >> $LOG 2>> $LOG
mount -t rootfs -o remount,rw rootfs >> $LOG 2>> $LOG
mount -o remount,rw -t auto /system >> $LOG 2>> $LOG
mount -o remount,rw /data >> $LOG 2>> $LOG
mount -o remount,rw /cache >> $LOG 2>> $LOG

	if [ $zap -eq 0 ]; then
		$box echo "1" > $count
		$box echo "First Boot, automatic space optimisation starts at 5th boot" >> $LOG
		exit

	elif [ $zap -eq 1 ]; then
		$box echo "2" > $count
		$box echo "Second Boot, automatic space optimisation starts at 5th boot" >> $LOG
		exit

	elif [ $zap -eq 2 ]; then
		$box echo "3" > $count
		$box echo "Third Boot, automatic space optimisation starts at 5th boot" >> $LOG
		exit

	elif [ $zap -eq 3 ]; then
		$box echo "4" > $count
		$box echo "Fourth Boot, automatic space optimisation starts at 5th boot" >> $LOG
		exit		

	elif [ $zap -eq  ]; then
		$box echo "0" > $count
	    $box echo "Fith Boot" >> $LOG
		$box echo "This log is as good as dead, so fml" >> $LOG

# Force recursive deletion of logs in /data/intelliboost/logs/
$box rm -rf /data/intelliboost/logs >> $LOG 2>> $LOG

# Force recursive deletion of verbose logging scripts in /system/etc/intelliboost
$box rm -rf /system/etc/intelliboost >> $LOG 2>> $LOG
mkdir /system/etc/intelliboost

# Move log-free clean scripts to run on boot from /data/logfreescripts to /system/etc/intelliboost, and set perms
mv -v /data/logfreescripts/* /system/etc/intelliboost >> $LOG 2>> $LOG
chmod -R ug+rw /system/etc/intelliboost >> $LOG 2>> $LOG

# Final cleanup
$box rm -rf /data/logfreescripts >> $LOG 2>> $LOG

# I'm already deleted on line 53, im just kept in memory as i am still being executed initially
# Bye anyways $box rm -rf /* :)
# Lol if i really did that it'll be such a troll lmao
# byeeeee....wait i still need to remount

mount -o remount,ro -t auto / >> $LOG 2>> $LOG
mount -t rootfs -o remount,ro rootfs >> $LOG 2>> $LOG
mount -o remount,ro -t auto /system >> $LOG 2>> $LOG
mount -o remount,rw /data >> $LOG 2>> $LOG
mount -o remount,rw /cache >> $LOG 2>> $LOG