#!/system/bin/sh
# Build.prop Tweaks (one time)

mount -o remount,rw -t auto /
mount -t rootfs -o remount,rw rootfs
mount -o remount,rw -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache

LOG=/data/intelliboost/logs/setprop.log
setprop=/system/etc/resourceIB/setprop
getprop=/system/etc/resourceIB/getprop

# Loop to reset log values
if [ -f \$LOG ]; then
busybox rm -f \$LOG;
touch \$LOG;
else
  touch \$LOG;
fi;

busybox echo "$( date +"%m-%d-%Y %H:%M:%S" )  Applying build.prop tweaks..." >> $LOG

# Wireless Speed Tweaks
$setprop net.tcp.buffersize.default 4096,87380,256960,4096,16384,256960 /system/build.prop
$setprop net.tcp.buffersize.wifi 4096,87380,256960,4096,16384,256960 /system/build.prop
$setprop net.tcp.buffersize.umts 4096,87380,256960,4096,16384,256960 /system/build.prop
$setprop net.tcp.buffersize.gprs 4096,87380,256960,4096,16384,256960 /system/build.prop
$setprop net.tcp.buffersize.edge 4096,87380,256960,4096,16384,256960 /system/build.prop

# Fast Dormancy
busybox echo "" >> $LOG
busybox echo "Activating fast dormancy..." >> $LOG
$setprop ro.fast.dormancy 1 /system/build.prop
$setprop ro.ril.fast.dormancy.rule 1 /system/build.prop
$setprop persist.radio.data_no_toggle 1 /system/build.prop
$setprop persist.cust.tel.eons 1 /system/build.prop
$setprop ro.config.hw_fast_dormancy 1 /system/build.prop
busybox echo "Fast dormancy is activated" >> $LOG
# Android Logcat totally disabled

# Much battery shall be saved
$setprop logcat.live disable /system/build.prop
busybox rm -f /dev/log/main
$setprop debugtool.anrhistory 0 /system/build.prop
$setprop profiler.debugmonitor false /system/build.prop
$setprop profiler.launch false /system/build.prop
$setprop profiler.hung.dumpdobugreport false /system/build.prop
$setprop persist.android.strictmode 0 /system/build.prop

#Graphics Tweaks and improvments
$setprop debug.performance.tuning 1 /system/build.prop
$setprop video.accelerate.hw 1 /system/build.prop
$setprop persist.sys.use_dithering 1 /system/build.prop
# Google DNS
# Security and stuff
# No effect on battery
# Google DNS
$setprop net.dns1 8.8.8.8 /system/build.prop
$setprop net.dns2 8.8.4.4 /system/build.prop
$setprop net.rmnet0.dns1 8.8.8.8 /system/build.prop
$setprop net.rmnet0.dns2 8.8.4.4 /system/build.prop
$setprop net.ppp0.dns1 8.8.8.8 /system/build.prop
$setprop net.ppp0.dns2 8.8.4.4 /system/build.prop
$setprop net.wlan0.dns1 8.8.8.8 /system/build.prop
$setprop net.wlan0.dns2 8.8.4.4 /system/build.prop
$setprop net.eth0.dns1 8.8.8.8 /system/build.prop
$setprop net.eth0.dns2 8.8.4.4 /system/build.prop
$setprop net.gprs.dns1 8.8.8.8 /system/build.prop
$setprop net.gprs.dns2 8.8.4.4 /system/build.prop

#Battery Tweaks
$setprop debug.sf.hw 1 /system/build.prop
$setprop ro.ril.power_collapse 0 /system/build.prop
$setprop ro.ril.disable.power.collapse 1 /system/build.prop
$setprop persist.sys.use_dithering 0 /system/build.prop
$setprop wifi.supplicant_scan_interval 250 /system/build.prop
$setprop power_supply.wakeup enable /system/build.prop
$setprop power.saving.mode 1 /system/build.prop
$setprop ro.config.hw_power_saving 1 /system/build.prop
$setprop ro.config.hw_power_saving true /system/build.prop
$setprop persist.radio.add_power_save 1 /system/build.prop
$setprop pm.sleep_mode 1 /system/build.prop
$setprop ro.ril.disable.power.collapse 0 /system/build.prop
$setprop ro.vold.umsdirtyratio 20 /system/build.prop
$setprop profiler.force_disable_err_rpt 1 /system/build.prop
$setprop profiler.force_disable_ulog 1 /system/build.prop
$setprop dalvik.vm.checkjni false /system/build.prop
$setprop dalvik.vm.execution-mode int:jit /system/build.prop
$setprop ro.ril.power_collapse 1 /system/build.prop
$setprop ro.mot.eri.losalert.delay 1000 /system/build.prop
# Purgable assets for fast reboot and battery save
$setprop persist.sys.purgeable_assets 1 /system/build.prop
# Slightly faster boot
$setprop ro.config.hw_quickpoweron true
# Net tweaks and RIL stuff
# Support for IPV4 and IPV6
$setprop persist.telephony.support.ipv6 1 /system/build.prop
$setprop persist.telephony.support.ipv4 1 /system/build.prop
busybox sysctl -w net.ipv4.conf.all.rp_filter 2 /system/build.prop
busybox sysctl -w net.ipv4.conf.default.rp_filter 2 /system/build.prop
busybox sysctl -w net.ipv4.tcp_max_syn_backlog 1024 /system/build.prop
busybox sysctl -w net.ipv4.tcp_synack_retries 2 /system/build.prop
#RIL Tweaks
$setprop ro.ril.hsxpa 3 /system/build.prop
$setprop ro.ril.gprsclass 12 /system/build.prop
$setprop ro.ril.hep 1 /system/build.prop
$setprop ro.ril.hsdpa.category 8 /system/build.prop
$setprop ro.ril.enable.3g.prefix 1 /system/build.prop
$setprop ro.ril.hsupa.category 6 /system/build.prop
$setprop ro.ril.enable.sdr 1 /system/build.prop
$setprop ro.ril.enable.gea3 1 /system/build.prop
$setprop ro.ril.enable.a52 0 /system/build.prop
$setprop ro.ril.enable.a53 1 /system/build.prop
# FFFFFAST 3G
$setprop ro.ril.hep 0 /system/build.prop
$setprop ro.ril.hsxpa 2 /system/build.prop
$setprop ro.ril.enable.dtm 1 /system/build.prop
$setprop ro.ril.htcmaskw1.bitmask 4294967295 /system/build.prop
$setprop ro.ril.htcmaskw1 14449 /system/build.prop
# Telephony
$setprop ro.telephony.call_ring.delay 0 /system/build.prop
$setprop ring.delay 0 /system/build.prop
# Disable Sending Usage Data
$setprop ro.config.nocheckin 1 /system/build.prop
#kernel tweaks (Disable error checking)
$setprop ro.kernel.android.checkjni 0 /system/build.prop
( while [ "$(getprop sys.boot_completed)" != 1 ]; do
sleep 20
done
#Optimal dex2oat threads for faster app installation
$setprop ro.sys.fw.dex2oat_thread_count 4 /system/build.prop
#Use 4 thread to improve dex2oat time
$setprop dalvik.vm.dex2oat-thread_count 4 /system/build.prop
$setprop dalvik.vm.dex2oat-threads 4 /system/build.prop

# Davlik VM tweaks on boot
$setprop jitdalvik.vm.checkjni false /system/build.prop
$setprop dalvik.vm.dexopt-data-only 1 /system/build.prop
$setprop dalvik.vm.heapstartsize 5m /system/build.prop
$setprop dalvik.vm.verify-bytecode false /system/build.prop
$setprop dalvik.vm.lockprof.threshold 250 /system/build.prop
$setprop dalvik.vm.dexopt-flags m=v,o=y /system/build.prop
$setprop dalvik.vm.jmiopts=forcecopy /system/build.prop

# uncertain if jit compiler will conflict with xposed framework
# higher heapgrowthlimit and heapsize values can make high mem games run lagless
# TODO: integrate this opyion into ui (not so sure if its on the fly)
RAM=$((` $box awk '/MemTotal/{print $2}' /proc/meminfo` / 1024 ))

setprop="/etc/Watson/setprop"
if [ "$RAM" -lt "512" ]
then
THRESHOLD=300
$setprop dalvik.vm.heaptargetutilization 0.9 /system/build.prop
else
THRESHOLD=250
$setprop dalvik.vm.heaptargetutilization 0.75 /system/build.prop
fi

HEAPMAXSIZE="$(( ($RAM * 244140 / 1000000) ))"
VMHEAP="$(( $HEAPMAXSIZE / ( 1000/$THRESHOLD ) ))"
$box busybox echo $VMHEAP

#set vm parameters
$box busybox echo "$RAM of system RAM detected" >> $LOGFILE
$box busybox echo "==> Max heap: ${HEAPMAXSIZE}m" >> $LOGFILE
$box busybox echo "==> Min heap: ${VMHEAP}m1" >> $LOGFILE
$setprop dalvik.vm.heapsize "${HEAPMAXSIZE}m" /system/build.prop
$setprop dalvik.vm.heapgrowthlimit "${VMHEAP}m" /system/build.prop
$setprop persist.sys.vm.heapsize "${VMHEAP}m" /system/build.prop

# UX
if [ "$RAM" -lt "512000" ]
then
$setprop persist.sys.force_highendgfx true /system/build.prop
$setprop ro.config.low_ram true /system/build.prop
fi

$setprop touch.pressure.scale 0.3 /system/build.prop
$setprop view.touch_slop 2 /system/build.prop
$setprop view.scroll_friction 1.5 /system/build.prop
$setprop ro.min_pointer_dur  8 /system/build.prop
$setprop touch.size.calibration geometric /system/build.prop
$setprop touch.size.scale 100 /system/build.prop
$setprop touch.size.bias 70 /system/build.prop
$setprop touch.pressure.calibration amplitude /system/build.prop
$setprop view.minimum_fling_velocity 25 /system/build.prop
$setprop ro.max.fling_velocity 12000 /system/build.prop
$setprop ro.min.fling_velocity 8000 /system/build.prop
$setprop ro.use_data_netmgrd true /system/build.prop
$setprop persist.data_netmgrd_nint 8 /system/build.prop
$setprop persist.data_netmgrd_mtu 1482 /system/build.prop
$setprop wifi.supplicant_scan_interval 180 /system/build.prop
$setprop pm.sleep_mode 1 /system/build.prop
$setprop ro.ril.disable.power.collapse 0 /system/build.prop

mount -o remount,ro -t auto /
mount -t rootfs -o remount,ro rootfs
mount -o remount,ro -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache