#!/system/bin/sh
# Fstrim on boot script

# LOG
LOG=/data/intelliboost/logs/fstrim.log
box=/system/xbin/busybox

# Loop to reset log values
if [ -f \$LOG ]; then
$box rm -f \$LOG;
touch \$LOG;
else
  touch \$LOG;
fi;

mount -o remount,rw -t auto / >> $LOG 2>> $LOG
mount -t rootfs -o remount,rw rootfs >> $LOG 2>> $LOG
mount -o remount,rw -t auto /system >> $LOG 2>> $LOG
mount -o remount,rw /data >> $LOG 2>> $LOG
mount -o remount,rw /cache >> $LOG 2>> $LOG

# Fstrim binary ($box applet)
# Current time is in enoch format

	$box echo "================================================" >> $LOG
	$box echo " Fstrim Start at $( date +"%m-%d-%Y %H:%M:%S" )" >> $LOG
	$box echo "================================================" >> $LOG

	$box fstrim -v /system >> $LOG 2>> $LOG
	$box fstrim -v /data >> $LOG 2>> $LOG
	$box fstrim -v /cache >> $LOG 2>> $LOG

	$box echo "================================================" >> $LOG
	$box echo " Fstrim Done at $( date +"%m-%d-%Y %H:%M:%S" )" >> $LOG
	$box echo "================================================" >> $LOG

mount -o remount,ro -t auto / >> $LOG 2>> $LOG
mount -t rootfs -o remount,ro rootfs >> $LOG 2>> $LOG
mount -o remount,ro -t auto /system >> $LOG 2>> $LOG
mount -o remount,rw /data >> $LOG 2>> $LOG
mount -o remount,rw /cache >> $LOG 2>> $LOG