#!/system/bin/sh
# Renicer
# With verbose logging
# TODO: Add more apps here

mount -o remount,rw -t auto /
mount -t rootfs -o remount,rw rootfs
mount -o remount,rw -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache

# Define vars
LOG=/data/intelliboost/logs/renice.log
getprop=/system/etc/resourceIB/getprop

# Loop to reset log values
if [ -f \$LOG ]; then
busybox rm -f \$LOG;
touch \$LOG;
else
  touch \$LOG;
fi;

(
while true
do

#Android's 'renice' binary is used here because it can only display the nice value of a process without changing.
busybox echo "SystemUI (com.android.systemui): previous scheduling info: $(renice -g $(pgrep com.android.systemui))" >> $LOG
busybox renice -10 $( pgrep com.android.systemui ) >> $LOG 2>> $LOG
busybox echo "SystemUI new scheduling info: $(renice -g $(pgrep com.android.systemui))">> $LOG

busybox echo "Zygote (zygote): previous scheduling info: $(renice -g $(pgrep zygote))" >> $LOG
busybox renice -8 $(pgrep zygote) >> $LOG 2>> $LOG
busybox echo "Zygote new scheduling info: $(renice -g $(pgrep zygote))">> $LOG

busybox echo "SurfaceFlinger (surfaceflinger): previous scheduling info: $(renice -g $(pgrep surfaceflinger))" >> $LOG
busybox renice -7 $(pgrep surfaceflinger) >> $LOG 2>> $LOG
busybox echo "SurfaceFlinger new scheduling info: $(renice -g $(pgrep surfaceflinger ))">> $LOG

busybox echo "System Server (system_server): previous scheduling info: $(renice -g $(pgrep system_server))" >> $LOG
busybox renice -7 $(pgrep system_server) >> $LOG 2>> $LOG
busybox echo "System Sever new scheduling info: $(renice -g $(pgrep system_server))">> $LOG

if pgrep com.google.android.gms
then
busybox echo "Google Play Services (com.google.android.gms): previous scheduling info: $(renice -g $(pgrep com.google.android.gms))" >> $LOG
busybox renice 19 $(pgrep com.google.android.gms) >> $LOG 2>> $LOG
busybox echo "Google Play Services new scheduling info: $(renice -g $(pgrep com.google.android.gms))">> $LOG
fi

if pgrep com.google.android.gsf
then
busybox echo "Google Services Framework (com.google.android.gsf): previous scheduling info: $(renice -g $(pgrep com.google.android.gsf))" >> $LOG
busybox renice 19 $(pgrep com.google.android.gsf) >> $LOG 2>> $LOG
busybox echo "Google Services Framework new scheduling info: $(renice -g $(pgrep com.google.android.gsf))">> $LOG
fi

if pgrep org.omnirom.omniswitch
then
busybox echo "OmniSwitch (org.omnirom.omniswitch): previous scheduling info: $(renice -g $(pgrep org.omnirom.omniswitch))" >> $LOG
busybox renice -11 $(pgrep org.omnirom.omniswitch) >> $LOG 2>> $LOG
busybox echo "OmniSwitch new scheduling info: $(renice -g $(pgrep org.omnirom.omniswitch))">> $LOG
fi

busybox echo "Apps reniced at $( date +"%m-%d-%Y %H:%M:%S" )" >> $LOG
done) &
