#!/system/bin/sh
# Google play services wakelock fix
# Kills aggressive wakelocks that drains a TON of battery

LOG=/data/intelliboost/logs/google.log
box=/system/xbin/busybox

# Loop to reset log values
if [ -f \$LOG ]; then
$box rm -f \$LOG;
$box touch \$LOG;
else
  $box touch \$LOG;
fi;

mount -o remount,rw -t auto / >> $LOG 2>> $LOG
mount -t rootfs -o remount,rw rootfs >> $LOG 2>> $LOG
mount -o remount,rw -t auto /system >> $LOG 2>> $LOG
mount -o remount,rw /data >> $LOG 2>> $LOG
mount -o remount,rw /cache >> $LOG 2>> $LOG

echo "$( date +"%m-%d-%Y %H:%M:%S" )  Google Play Services wakelock drain fix..." >> $LOG
$box echo "" >> $LOG
$box echo "Activating Google Play Services Drain fix..." >> $LOG
su -c pm enable com.google.android.gms/.update.SystemUpdateActivity >> $LOG 2>> $LOG
su -c pm enable com.google.android.gms/.update.SystemUpdateService >> $LOG 2>> $LOG
su -c pm enable com.google.android.gms/.update.SystemUpdateService\$ActiveReceiver >> $LOG 2>> $LOG
su -c pm enable com.google.android.gms/.update.SystemUpdateService\$Receiver >> $LOG 2>> $LOG
su -c pm enable com.google.android.gms/.update.SystemUpdateService\$SecretCodeReceiver >> $LOG 2>> $LOG
su -c pm enable com.google.android.gsf/.update.SystemUpdateActivity >> $LOG 2>> $LOG
su -c pm enable com.google.android.gsf/.update.SystemUpdatePanoActivity >> $LOG 2>> $LOG
su -c pm enable com.google.android.gsf/.update.SystemUpdateService >> $LOG 2>> $LOG
su -c pm enable com.google.android.gsf/.update.SystemUpdateService\$Receiver >> $LOG 2>> $LOG
su -c pm enable com.google.android.gsf/.update.SystemUpdateService\$SecretCodeReceiver >> $LOG 2>> $LOG

$box sleep 20

$box echo "Killing Gapps battery draining processes..." >> $LOG
$box killall -9 com.google.android.gms >> $LOG 2>> $LOG
$box killall -9 com.google.android.gms.persistent >> $LOG 2>> $LOG
$box killall -9 com.google.process.gapps >> $LOG 2>> $LOG
$box killall -9 com.google.android.gsf >> $LOG 2>> $LOG
$box killall -9 com.google.android.gsf.persistent >> $LOG 2>> $LOG
$box echo "They died lol :)" >> $LOG
$box echo "Google Play Services Drain fix complete!" >> $LOG

mount -o remount,ro -t auto / >> $LOG 2>> $LOG
mount -t rootfs -o remount,ro rootfs >> $LOG 2>> $LOG
mount -o remount,ro -t auto /system >> $LOG 2>> $LOG
mount -o remount,rw /data >> $LOG 2>> $LOG
mount -o remount,rw /cache >> $LOG 2>> $LOG