#!/system/bin/sh
# Cleaner script

#setvar
LOG=/data/intelliboost/logs/cleaner.log
box=/system/xbin/busybox
mount -o remount,rw -t auto / >> $LOG 2>> $LOG
mount -t rootfs -o remount,rw rootfs >> $LOG 2>> $LOG
mount -o remount,rw -t auto /system >> $LOG 2>> $LOG
mount -o remount,rw /data >> $LOG 2>> $LOG
mount -o remount,rw /cache >> $LOG 2>> $LOG
# Loop to reset log values
if [ -rf \$LOG ]; then
$box rm -f \$LOG;
$box touch \$LOG;
else
  $box touch \$LOG;
fi;
#make clean
start at:
$( date +"%m-%d-%Y %H:%M:%S" )
$box echo "Cleaning Up Junk Files..." >> $LOG
clear
sync
$box echo "3" > /proc/sys/vm/drop_caches
dc=/proc/sys/vm/drop_caches
dc_v=`cat $dc`
if [ "$dc_v" -gt 1 ]; then
   $box echo "1" > /proc/sys/vm/drop_caches
fi
# cleaner
$box rm -rf /data/anr/*.* >> $LOG 2>> $LOG
$box rm -rf /data/cache/*.* >> $LOG 2>> $LOG
$box rm -rf /data/log/*.* >> $LOG 2>> $LOG
$box rm -rf /data/local/tmp/*.* >> $LOG 2>> $LOG
$box rm -rf /data/mlog/* >> $LOG 2>> $LOG
$box rm -rf /data/tombstones/* >> $LOG 2>> $LOG
$box rm -rf /data/backup/pending/* >> $LOG 2>> $LOG
$box rm -rf /data/system/dropbox/* >> $LOG 2>> $LOG
chmod 700 /data/system/dropbox >> $LOG 2>> $LOG
$box rm -rf /data/system/usagestats/* >> $LOG 2>> $LOG
$box chmod 700 /data/system/usagestats >> $LOG 2>> $LOG
$box rm -rf /data/local/*.apk >> $LOG 2>> $LOG
$box rm -rf /data/local/tmp/*.apk >> $LOG 2>> $LOG
$box rm -rf /data/*.log >> $LOG 2>> $LOG
$box rm -rf /data/log/*.log >> $LOG 2>> $LOG
$box rm -rf /cache/* >> $LOG 2>> $LOG
$box rm -rf /cache/recovery/* >> $LOG 2>> $LOG
$box rm -rf /data/system/dropbox/*.txt >> $LOG 2>> $LOG
$box rm -rf /data/backup/pending/*.tmp >> $LOG 2>> $LOG
$box rm -rf /sdcard/LOST.DIR/* >> $LOG 2>> $LOG
export sampling_rate=10000
export up_threshold=80
$box echo "Successfully cleaned up junk!" >> $LOG
if [ -e /data/anr/*.* ]; then
  $box echo "-anr not cleaned" >> $LOG
 else
  $box echo "-anr cleaned" >> $LOG
if [ -e /data/local/tmp/*.* ]; then
  $box echo "-local/tmp not cleaned" >> $LOG
  $box echo "-local/tmp cleaned" >> $LOG
if [ -e /data/cache/*.* ]; then
  $box echo "-cache not cleaned" >> $LOG
  $box echo "-cache cleaned" >> $LOG
if [ -e /data/last_log/*.* ]; then
  $box echo "-log not cleaned" >> $LOG
  $box echo "-log cleaned" >> $LOG
if [ -e /data/tombstones/*.* ]; then
  $box echo "-tombstones not cleaned" >> $LOG
  $box echo "-tombstones cleaned" >> $LOG
# end
$box echo "cleaned at $( date +"%m-%d-%Y %H:%M:%S" )" >> $LOG
mount -o remount,ro -t auto / >> $LOG 2>> $LOG
mount -t rootfs -o remount,ro rootfs >> $LOG 2>> $LOG
mount -o remount,ro -t auto /system >> $LOG 2>> $LOG