#!/system/bin/sh
# LMK DEFAULT SCRIPT

# OOM killer and priority fixes
# Low memory killer and out of memory killer (LMK & OOM)
# Low mem killer(lmk)

# TODO: Dynamic lmk

#Setvar
LOG=/data/intelliboost/logs/lmk.log
box=/system/xbin/busybox

# Loop to reset log values
if [ -f \$LOG ]; then
$box rm -f \$LOG;
$box touch \$LOG;
else
  $box touch \$LOG;
fi;

mount -o remount,rw -t auto / >> $LOG 2>> $LOG
mount -t rootfs -o remount,rw rootfs >> $LOG 2>> $LOG
mount -o remount,rw -t auto /system >> $LOG 2>> $LOG
mount -o remount,rw /data >> $LOG 2>> $LOG
mount -o remount,rw /cache >> $LOG 2>> $LOG

$box echo "Tweaking minfree, cost & debug values..." >> $LOG

# Cost
if [ -e /sys/module/lowmemorykiller/parameters/cost ]; then
$box chmod 644 /sys/module/lowmemorykiller/parameters/cost >> $LOG 2>> $LOG
$box echo "64" > /sys/module/lowmemorykiller/parameters/cost >> $LOG 2>> $LOG
fi
# Minfree Values
RAM=\$((\$($box awk '/MemTotal/{print \$2}' /proc/meminfo)/1024))
lmk1=\$((RAM*2*1024/100/4));
lmk2=\$((RAM*3*1024/100/4));
lmk3=\$((RAM*4*1024/100/4));
lmk4=\$((RAM*5*1024/100/4));
lmk5=\$((RAM*6*1024/100/4));
lmk6=\$((RAM*7*1024/100/4));
$box chmod 644 /sys/module/lowmemorykiller/parameters/minfree >> $LOG 2>> $LOG
$box echo "\$lmk1,\$lmk2,\$lmk3,\$lmk4,\$lmk5,\$lmk6" > /sys/module/lowmemorykiller/parameters/minfree
$box echo "" >> $LOG
$box echo "Multitasking RAM manager for \$RAM mb devices successfully applied.." >> $LOG

# Enable OOM Killer
# Might cause FCs if you have low ram running high quality games
# Saves battery in return

$box sysctl -e -w vm.oom_dump_tasks=1 >> $LOG 2>> $LOG
$box sysctl -e -w vm.oom_kill_allocating_task=1 >> $LOG 2>> $LOG

# ADJ Values
$box echo "0,1,3,5,7,15" > /sys/module/lowmemorykiller/parameters/adj >> $LOG 2>> $LOG

mount -o remount,ro -t auto / >> $LOG 2>> $LOG
mount -t rootfs -o remount,ro rootfs >> $LOG 2>> $LOG
mount -o remount,ro -t auto /system >> $LOG 2>> $LOG
mount -o remount,rw /data >> $LOG 2>> $LOG
mount -o remount,rw /cache >> $LOG 2>> $LOG