#!/system/bin/sh
mount -o remount,rw -t auto /
mount -t rootfs -o remount,rw rootfs
mount -o remount,rw -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache
readahead_kb="512"
if [ -e /sys/devices/virtual/bdi/0:18/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/0:18/readahead_kb
fi

if [ -e /sys/devices/virtual/bdi/179:0/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/179:0/readahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:0/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:0/readahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:1/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:1/readahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:2/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:2/readahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:3/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:3/readahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:4/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:4/readahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:5/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:5/readahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:6/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:6/readahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:7/readahead_kb ]; then
    echo $readahead_kb > /sys/devices/virtual/bdi/7:7/readahead_kb

fi
if [ -e /sys/devices/virtual/bdi/default/readahead_kb ]; then
    echo "256" > /sys/devices/virtual/bdi/default/readahead_kb
fi
mount -o remount,ro -t auto /
mount -t rootfs -o remount,ro rootfs
mount -o remount,ro -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache