#!/system/bin/sh
mount -o remount,rw -t auto /
mount -t rootfs -o remount,rw rootfs
mount -o remount,rw -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache
if [ pgrep qrngd > /dev/null ]; then
  exit 1
fi
if [ -e /system/bin/qrngd -o -e /system/xbin/qrngd ]; then
  exit 1
fi
rngd -t 2 -T 1 -s 256 --fill-watermark=80%
busybox sleep 2
echo -8 > /proc/$(pgrep rngd)/oom_adj
renice 5 `pidof rngd`
busybox sysctl -e -w kernel.random.read_wakeup_threshold=128
busybox sysctl -e -w kernel.random.write_wakeup_threshold=256
busybox sleep 1
if [ grep "128" proc/sys/kernel/random/read_wakeup_threshold ]; then
else
fi
mount -o remount,ro -t auto /
mount -t rootfs -o remount,ro rootfs
mount -o remount,ro -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache