#!/system/bin/sh
mount -o remount,rw -t auto /
mount -t rootfs -o remount,rw rootfs
mount -o remount,rw -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache
	CNT=/data/intelliboost/sqlitecnt
	SC=`cat $CNT`
	if [ $SC -eq 0 ]; then
		busybox echo "1" > $CNT
		busybox echo "First Boot"
		exit
	elif [ $SC -eq 1 ]; then
		busybox echo "2" > $CNT
	fi;
	elif [ $SC -eq 2 ]; then
	for i in `busybox find /d* -iname "*.db"`; do
		/system/xbin/sqlite3 $i 'VACUUM;';
		resVac=$?
		if [ $resVac == 0 ]; then
			resVac="SUCCESS";
		else
			resVac="ERRCODE-$resVac";
		fi;
		/system/xbin/sqlite3 $i 'REINDEX;';
		resIndex=$?
		if [ $resIndex == 0 ]; then
			resIndex="SUCCESS";
		else
			resIndex="ERRCODE-$resIndex";
		fi;
		busybox echo "Database $i:  VACUUM=$resVac  REINDEX=$resIndex";
	done;
fi
mount -o remount,ro -t auto /
mount -t rootfs -o remount,ro rootfs
mount -o remount,ro -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache