#!/system/bin/sh
# Loop optimising space use (why am i doing this lmao)

mount -o remount,rw -t auto /
mount -t rootfs -o remount,rw rootfs
mount -o remount,rw -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache
count=/data/intelliboost/loop
zap=`cat $count`
	if [ $zap -eq 0 ]; then
		busybox echo "1" > $count
		busybox echo "First Boot, automatic space optimisation starts at 5th boot"
		exit

	elif [ $zap -eq 1 ]; then
		busybox echo "2" > $count
		busybox echo "Second Boot, automatic space optimisation starts at 5th boot"
		exit

	elif [ $zap -eq 2 ]; then
		busybox echo "3" > $count
		busybox echo "Third Boot, automatic space optimisation starts at 5th boot"
		exit

	elif [ $zap -eq 3 ]; then
		busybox echo "4" > $count
		busybox echo "Fourth Boot, automatic space optimisation starts at 5th boot"
		exit		

	elif [ $zap -eq  ]; then
		busybox echo "0" > $count
        busybox rm -rf /data/intelliboost/logs
        busybox rm -rf /system/etc/intelliboost
        mkdir /system/etc/intelliboost
        mv -v /data/logfreescripts/* /system/etc/intelliboost
        chmod -R ug+rw /system/etc/intelliboost
        busybox rm -rf /data/logfreescripts
mount -o remount,ro -t auto /
mount -t rootfs -o remount,ro rootfs
mount -o remount,ro -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache