#!/system/bin/sh
mount -o remount,rw -t auto /
mount -t rootfs -o remount,rw rootfs
mount -o remount,rw -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache
ZIPALIGNDB=/data/zipalign.db
count=/data/intelliboost/zipaligncnt
zap=`cat $count`
if [ ! -f $ZIPALIGNDB ]; then
	touch $ZIPALIGNDB;
fi;
  if [ $zap -eq 0 ]; then
    busybox echo "1" > $count
    exit

  elif [ $zap -eq 1 ]; then
    busybox echo "2" > $count
    exit

  elif [ $zap -eq 2 ]; then
    busybox echo "0" > $count
for DIR in /system/app /data/app ; do
  cd $DIR
  for APK in *.apk ; do
    if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ] ; then
    else
      zipalign -c 4 $APK
      if [ $? -eq 0 ] ; then
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || busybox echo $DIR/$APK >> $ZIPALIGNDB
      else
        zipalign -f 4 $APK /cache/$APK
        busybox mount -o rw,remount /system
        cp -f -p /cache/$APK $APK
        busybox rm -f /cache/$APK
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || busybox echo $DIR/$APK >> $ZIPALIGNDB
      fi
    fi
  done
done
rm -f $ZIPALIGNDB
touch $ZIPALIGNDB
mount -o remount,ro -t auto /
mount -t rootfs -o remount,ro rootfs
mount -o remount,ro -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache