#!/system/bin/sh
mount -o remount,rw -t auto /
mount -t rootfs -o remount,rw rootfs
mount -o remount,rw -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache
busybox rm -f /data/anr/*.*
busybox rm -f /data/cache/*.*
busybox rm -f /data/log/*.*
busybox rm -f /data/local/tmp/*.*
busybox rm -f /data/mlog/*
busybox rm -f /data/tombstones/*
busybox rm -f /data/backup/pending/*
busybox rm -f /data/system/dropbox/*
chmod 700 /data/system/dropbox
busybox rm -f /data/system/usagestats/*
busybox chmod 700 /data/system/usagestats
export sampling_rate=10000
export up_threshold=80
if [ -e /data/anr/*.* ]; then
  busybox echo "-anr not cleaned" | busybox tee -a $LOG; else
  busybox echo "-anr cleaned" | busybox tee -a $LOG
fi;
if [ -e /data/local/tmp/*.* ]; then
  busybox echo "-local/tmp not cleaned" | busybox tee -a $LOG; else
  busybox echo "-local/tmp cleaned" | busybox tee -a $LOG
fi;
if [ -e /data/cache/*.* ]; then
  busybox echo "-cache not cleaned" | busybox tee -a $LOG; else
  busybox echo "-cache cleaned" | busybox tee -a $LOG
fi;
if [ -e /data/last_log/*.* ]; then
  busybox echo "-log not cleaned" | busybox tee -a $LOG; else
  busybox echo "-log cleaned" | busybox tee -a $LOG
fi;
if [ -e /data/tombstones/*.* ]; then
  busybox echo "-tombstones not cleaned" | busybox tee -a $LOG; else
  busybox echo "-tombstones cleaned" | busybox tee -a $LOG
fi;

# end
busybox echo "cleaned at$( date +"%m-%d-%Y %H:%M:%S" )" | busybox tee -a $LOG;

mount -o remount,ro -t auto /
mount -t rootfs -o remount,ro rootfs
mount -o remount,ro -t auto /system
mount -o remount,rw /data
mount -o remount,rw /cache