#!/system/bin/sh

LOG=/data/intelliboost/seeder.log

#reload log
if [ -f \$LOG ]; then
busybox rm \$LOG;
fi;

if [ pgrep qrngd > /dev/null ]; then
 busybox echo "qrngd already running! Seeder will not be started!" >> $LOG
  exit 1
fi

if [ -e /system/bin/qrngd -o -e /system/xbin/qrngd ]; then
 busybox echo "qrngd found in /system! Seeder will not be started!" >> $LOG
  exit 1
fi

rngd -t 2 -T 1 -s 256 --fill-watermark=80%
sleep 2busybox
echo -8 > /proc/$(pgrep rngd)/oom_adj
renice 5 `pidof rngd`

busybox echo "Activating battery saving seeder profile.." | busybox tee -a \$LOG
busybox sysctl -e -w kernel.random.read_wakeup_threshold=128
busybox sysctl -e -w kernel.random.write_wakeup_threshold=256

busybox sleep 1
if [ grep "128" proc/sys/kernel/random/read_wakeup_threshold ]; then
busybox echo "Light seeder profile is activated.." | busybox tee -a \$LOG
else
busybox echo "Light seeder profile is not activated.." | busybox tee -a \$LOG
fi