#!/system/bin/sh
# light light seeder
# Copyright (C) 2017 @ala_mo
#=======================================================================#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#=======================================================================#

# NOTE: values set might be too aggro, make sure sugar is kept a safe distance...

LOG=/data/intelliboost/seeder.log

# Loop to reset log values
if [ -f \$LOG ]; then
busybox rm \$LOG;
touch \$LOG;
else
	touch \$LOG;
fi;

#reload log
if [ -f \$LOG ]; then
busybox rm \$LOG;
fi;

if [ pgrep qrngd > /dev/null ]; then
 busybox echo "qrngd already running! Seeder will not be started!" >> $LOG
  exit 1
fi

if [ -e /system/bin/qrngd -o -e /system/xbin/qrngd ]; then
 busybox echo "qrngd found in /system! Seeder will not be started!" >> $LOG
  exit 1
fi

rngd -t 2 -T 1 -s 256 --fill-watermark=80%
sleep 2busybox
echo -8 > /proc/$(pgrep rngd)/oom_adj
renice 5 `pidof rngd`

busybox echo "Activating battery saving seeder profile.." | busybox tee -a \$LOG
busybox sysctl -e -w kernel.random.read_wakeup_threshold=128
busybox sysctl -e -w kernel.random.write_wakeup_threshold=256

busybox sleep 1
if [ grep "128" proc/sys/kernel/random/read_wakeup_threshold ]; then
busybox echo "Light seeder profile is activated.." | busybox tee -a \$LOG
else
busybox echo "Light seeder profile is not activated.." | busybox tee -a \$LOG
fi