#!/system/bin/sh
# LMK DEFAULT SCRIPT
# Copyright (C) 2017 @ala_mo
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

# OOM killer and priority fixes
# Low memory killer and out of memory killer (LMK & OOM)
# Low mem killer(lmk)

# TODO: Dynamic lmk

LOG=/data/intelliboost/lmk.log
if [ -f \$LOG ]; then
busybox rm \$LOG;
touch \$LOG;
fi;

busybox mount -o remount,ro / 2>/dev/null
busybox mount -o remount,ro / / 2>/dev/null
busybox mount -o remount,ro rootfs 2>/dev/null
busybox mount -o remount,ro /system 2>/dev/null
busybox mount -o remount,ro /system /system 2>/dev/null

busybox echo "Tweaking minfree, cost & debug values..." | busybox tee -a \$LOG
# Cost
if [ -e /sys/module/lowmemorykiller/parameters/cost ]; then
busybox chmod 644 /sys/module/lowmemorykiller/parameters/cost
busybox echo "64" > /sys/module/lowmemorykiller/parameters/cost
fi
# Minfree Values
RAM=\$((\$(busybox awk '/MemTotal/{print \$2}' /proc/meminfo)/1024))
lmk1=\$((RAM*2*1024/100/4));
lmk2=\$((RAM*3*1024/100/4));
lmk3=\$((RAM*4*1024/100/4));
lmk4=\$((RAM*5*1024/100/4));
lmk5=\$((RAM*6*1024/100/4));
lmk6=\$((RAM*7*1024/100/4));
busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
busybox echo "\$lmk1,\$lmk2,\$lmk3,\$lmk4,\$lmk5,\$lmk6" > /sys/module/lowmemorykiller/parameters/minfree
busybox echo "" | busybox tee -a \$LOG
busybox echo "Multitasking RAM manager for \$RAM mb devices successfully applied.." | busybox tee -a \$LOG

# Enable OOM Killer
# Might cause FCs if you have low ram running high quality games
busybox sysctl -e -w vm.oom_dump_tasks=1
busybox sysctl -e -w vm.oom_kill_allocating_task=1
# Saves battery in return

# ADJ Values
echo "0,1,3,5,7,15" > /sys/module/lowmemorykiller/parameters/adj;

