#!/system/bin/sh

#low mem killer
LS=/system/L_SPEED/LOGS/LS00RAM_Manager.log
if [ -f \$LS ]; then
busybox rm \$LS;
fi;
busybox echo "# L Speed log " | busybox tee -a \$LS
busybox echo "" | busybox tee -a \$LS
busybox echo "Tweaking minfree, cost & debug values..." | busybox tee -a \$LS
# Cost
if [ -e /sys/module/lowmemorykiller/parameters/cost ]; then
busybox chmod 644 /sys/module/lowmemorykiller/parameters/cost
busybox echo "64" > /sys/module/lowmemorykiller/parameters/cost
fi
# Minfree Values
RAM=\$((\$(busybox awk '/MemTotal/{print \$2}' /proc/meminfo)/1024))
lmk1=\$((RAM*2*1024/100/4));
lmk2=\$((RAM*3*1024/100/4));
lmk3=\$((RAM*4*1024/100/4));
lmk4=\$((RAM*5*1024/100/4));
lmk5=\$((RAM*6*1024/100/4));
lmk6=\$((RAM*7*1024/100/4));
busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
busybox echo "\$lmk1,\$lmk2,\$lmk3,\$lmk4,\$lmk5,\$lmk6" > /sys/module/lowmemorykiller/parameters/minfree
busybox echo "" | busybox tee -a \$LS
busybox echo "Multitasking RAM manager for \$RAM mb devices successfully applied.." | busybox tee -a \$LS

# ADJ Values
echo "0,1,3,5,7,15" > /sys/module/lowmemorykiller/parameters/adj;

# Minfree Values (80mb)
echo "1280,2560,5120,7680,12800,20480" > /sys/module/lowmemorykiller/parameters/minfree;
