#!/system/bin/sh
# Fstrim on boot script
# Copyright (C) 2017 @ala_mo
#=======================================================================#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#=======================================================================#

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
mount -o remount,rw /data
mount -o remount,rw /cache

# LOG
LOG=/data/intelliboost/fstrim.log

# Loop to reset log values
if [ -f \$LOG ]; then
busybox rm \$LOG;
touch \$LOG;
else
	touch \$LOG;
fi;

# Fstrim binary (busybox applet)
# Current time is in enoch format

if [ -e /system/bin/fstrim ] || [ -e /system/xbin/fstrim ] || [ -e /sbin/fstrim ];
then
	echo "================================================" | tee -a $LOG
	echo " Fstrim Start at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG
	echo "================================================" | tee -a $LOG

	fstrim -v /system | tee -a $LOG;
	fstrim -v /data | tee -a $LOG;
	fstrim -v /cache | tee -a $LOG;

	echo "================================================" | tee -a $LOG
	echo " Fstrim Done at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG
	echo "================================================" | tee -a $LOG
else
	echo "* Fstrim can't run without Busybox, Please install busybox (playstore) !" | tee -a $LOG
fi
