#!/system/bin/sh
# Fstrim on boot script
# Copyright (C) 2017 @ala_mo
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
mount -o remount,rw /data
mount -o remount,rw /cache

# LOG
LOG=/data/intelliboost/fstrim.log
if [ -e $LOG ];
then
	rm -f $LOG
fi

# Fstrim binary (busybox applet)
# Current time is in enoch format

if [ -e /system/bin/fstrim ] || [ -e /system/xbin/fstrim ] || [ -e /sbin/fstrim ];
then
	echo "================================================" | tee -a $LOG
	echo " Fstrim Start at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG
	echo "================================================" | tee -a $LOG

	fstrim -v /system | tee -a $LOG;
	fstrim -v /data | tee -a $LOG;
	fstrim -v /cache | tee -a $LOG;

	echo "================================================" | tee -a $LOG
	echo " Fstrim Done at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG
	echo "================================================" | tee -a $LOG
else
	echo "* Fstrim can't run without Busybox, Please install busybox (playstore) !" | tee -a $LOG
fi
