#!/system/bin/sh
# Assertive display script
# Copyright (C) 2017 @ala_mo
#=======================================================================#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#=======================================================================#

# No logging cuase of one time shot

Qualcomm=`cat /system/build.prop|grep "MSM"`

if [ "$Qualcomm" ]; 
then 
	echo "Qualcomm device detected! Applying..."

	mount -o remount,rw /system
	echo "
	" >> /system/build.prop
	echo "# Assertive Display #" >> /system/build.prop
	echo "# To save Battery by reducing backlight" >> /system/build.prop
	echo "# Only for Qualcomm :)" >> /system/build.prop
	echo "ro.qcom.ad=1
ro.qcom.ad.calib.data=/system/etc/ad_calib.cfg" >> /system/build.prop
    echo "By @ala_mo" >> /system/build.prop
	mount -o remount,ro /system
fi;
# Delete myself :)
rm -f /system/etc/69assert

echo "" | tee -a \$LOG
echo "" | tee -a \$LOG
echo "I just killed myself" | tee -a \$LOG
echo "This is the last time i will be executed (pun intended)" | tee -a \$LOG
echo "Goodbye my friends, i have done my job" | tee -a \$LOG
echo "But i have 1 last request" | tee -a \$LOG
echo "." | tee -a \$LOG
echo "." | tee -a \$LOG
echo "." | tee -a \$LOG
echo "Please delete my browser history :)" | tee -a \$LOG
