#!/system/bin/sh
#Assertive display script
# Copyright (C) 2017 @ala_mo
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

Qualcomm=`cat /system/build.prop|grep "MSM"`

if [ "$Qualcomm" ]; 
then 
	echo "Qualcomm device detected! Applying..."

	mount -o remount,rw /system
	echo "
	" >> /system/build.prop
	echo "# Assertive Display #" >> /system/build.prop
	echo "# To save Battery by reducing backlight" >> /system/build.prop
	echo "# Only for Qualcomm :)" >> /system/build.prop
	echo "ro.qcom.ad=1
ro.qcom.ad.calib.data=/system/etc/ad_calib.cfg" >> /system/build.prop
    echo "By @ala_mo" >> /system/build.prop
	mount -o remount,ro /system
fi;
# Delete myself :)
rm -f /system/etc/69assert

echo "" | tee -a \$LOG
echo "" | tee -a \$LOG
echo "I just killed myself" | tee -a \$LOG
echo "This is the last time i will be executed (pun intended)" | tee -a \$LOG
echo "Goodbye my friends, i have done my job" | tee -a \$LOG
echo "But i have 1 last request" | tee -a \$LOG
echo "." | tee -a \$LOG
echo "." | tee -a \$LOG
echo "." | tee -a \$LOG
echo "Please delete my browser history :)" | tee -a \$LOG
