#!/system/bin/sh
# Google Services Drain Fix
# Copyright (C) 2017 @ala_mo
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox mount -o remount,rw / 2>/dev/null
busybox mount -o remount,rw / / 2>/dev/null
busybox mount -o remount,rw rootfs 2>/dev/null
busybox mount -o remount,rw /system 2>/dev/null
busybox mount -o remount,rw /system /system 2>/dev/null
LOG=/data/intelliboost/google.log
if [ -f \$LOG ]; then
busybox rm \$LOG;
fi;
echo "$( date +"%m-%d-%Y %H:%M:%S" )  Google Play Services Drain fix..." | tee -a $LOG;
busybox echo "" | busybox tee -a \$LOG
busybox echo "Activating Google Play Services Drain fix..." | busybox tee -a \$LOG
su -c pm enable com.google.android.gms/.update.SystemUpdateActivity
su -c pm enable com.google.android.gms/.update.SystemUpdateService
su -c pm enable com.google.android.gms/.update.SystemUpdateService\$ActiveReceiver
su -c pm enable com.google.android.gms/.update.SystemUpdateService\$Receiver
su -c pm enable com.google.android.gms/.update.SystemUpdateService\$SecretCodeReceiver
su -c pm enable com.google.android.gsf/.update.SystemUpdateActivity
su -c pm enable com.google.android.gsf/.update.SystemUpdatePanoActivity
su -c pm enable com.google.android.gsf/.update.SystemUpdateService
su -c pm enable com.google.android.gsf/.update.SystemUpdateService\$Receiver
su -c pm enable com.google.android.gsf/.update.SystemUpdateService\$SecretCodeReceiver

busybox sleep 20
busybox echo "Killing Gapps battery draining processes..." | busybox tee -a \$LOG
busybox killall -9 com.google.android.gms
busybox killall -9 com.google.android.gms.persistent
busybox killall -9 com.google.process.gapps
busybox killall -9 com.google.android.gsf
busybox killall -9 com.google.android.gsf.persistent
busybox echo "Done!" | busybox tee -a \$LOG

busybox mount -o remount,ro / 2>/dev/null
busybox mount -o remount,ro / / 2>/dev/null
busybox mount -o remount,ro rootfs 2>/dev/null
busybox mount -o remount,ro /system 2>/dev/null
busybox mount -o remount,ro /system /system 2>/dev/null

busybox echo "Google Play Services Drain fix" | busybox tee -a \$LOG
