#!/system/bin/sh
# Google Services Drain Fix
# Copyright (C) 2017 @ala_mo
#=======================================================================#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#=======================================================================#

busybox mount -o remount,rw / 2>/dev/null
busybox mount -o remount,rw / / 2>/dev/null
busybox mount -o remount,rw rootfs 2>/dev/null
busybox mount -o remount,rw /system 2>/dev/null
busybox mount -o remount,rw /system /system 2>/dev/null

LOG=/data/intelliboost/google.log

# Loop to reset log values
if [ -f \$LOG ]; then
busybox rm \$LOG;
touch \$LOG;
else
	touch \$LOG;
fi;

echo "$( date +"%m-%d-%Y %H:%M:%S" )  Google Play Services Drain fix..." | tee -a $LOG;
busybox echo "" | busybox tee -a \$LOG
busybox echo "Activating Google Play Services Drain fix..." | busybox tee -a \$LOG
su -c pm enable com.google.android.gms/.update.SystemUpdateActivity
su -c pm enable com.google.android.gms/.update.SystemUpdateService
su -c pm enable com.google.android.gms/.update.SystemUpdateService\$ActiveReceiver
su -c pm enable com.google.android.gms/.update.SystemUpdateService\$Receiver
su -c pm enable com.google.android.gms/.update.SystemUpdateService\$SecretCodeReceiver
su -c pm enable com.google.android.gsf/.update.SystemUpdateActivity
su -c pm enable com.google.android.gsf/.update.SystemUpdatePanoActivity
su -c pm enable com.google.android.gsf/.update.SystemUpdateService
su -c pm enable com.google.android.gsf/.update.SystemUpdateService\$Receiver
su -c pm enable com.google.android.gsf/.update.SystemUpdateService\$SecretCodeReceiver

busybox sleep 20
busybox echo "Killing Gapps battery draining processes..." | busybox tee -a \$LOG
busybox killall -9 com.google.android.gms
busybox killall -9 com.google.android.gms.persistent
busybox killall -9 com.google.process.gapps
busybox killall -9 com.google.android.gsf
busybox killall -9 com.google.android.gsf.persistent
busybox echo "Done!" | busybox tee -a \$LOG

busybox mount -o remount,ro / 2>/dev/null
busybox mount -o remount,ro / / 2>/dev/null
busybox mount -o remount,ro rootfs 2>/dev/null
busybox mount -o remount,ro /system 2>/dev/null
busybox mount -o remount,ro /system /system 2>/dev/null

busybox echo "Google Play Services Drain fix" | busybox tee -a \$LOG
