#!/system/bin/sh
# Cleaner script
# Copyright (C) 2017 @ala_mo
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

LOG=/data/intelliboost/cleaner.log

    if [ -e $LOG ]; then
        rm $LOG;
    fi;


#make clean
start at:
$( date +"%m-%d-%Y %H:%M:%S" )


# cleaner
busybox rm -f /data/anr/*.*
busybox rm -f /data/cache/*.*
busybox rm -f /data/log/*.*
busybox rm -f /data/local/tmp/*.*
busybox rm -f /data/mlog/*
busybox rm -f /data/tombstones/*
busybox rm -f /data/backup/pending/*
busybox rm -f /data/system/dropbox/*
chmod 700 /data/system/dropbox
busybox rm -f /data/system/usagestats/*
busybox chmod 700 /data/system/usagestats

export sampling_rate=10000
export up_threshold=80


busybox echo "Successfully cleaned up junk!" | busybox tee -a $LOG;

if [ -e /data/anr/*.* ]; then
  busybox echo "-anr not cleaned" | busybox tee -a $LOG; else
  busybox echo "-anr cleaned" | busybox tee -a $LOG
fi;
if [ -e /data/local/tmp/*.* ]; then
  busybox echo "-local/tmp not cleaned" | busybox tee -a $LOG; else
  busybox echo "-local/tmp cleaned" | busybox tee -a $LOG
fi;
if [ -e /data/cache/*.* ]; then
  busybox echo "-cache not cleaned" | busybox tee -a $LOG; else
  busybox echo "-cache cleaned" | busybox tee -a $LOG
fi;
if [ -e /data/last_log/*.* ]; then
  busybox echo "-log not cleaned" | busybox tee -a $LOG; else
  busybox echo "-log cleaned" | busybox tee -a $LOG
fi;
if [ -e /data/tombstones/*.* ]; then
  busybox echo "-tombstones not cleaned" | busybox tee -a $LOG; else
  busybox echo "-tombstones cleaned" | busybox tee -a $LOG
fi;

busybox echo "Failed? Install busybox!!!!!!!! " | busybox tee -a $LOG
# end
busybox echo "cleaned at$( date +"%m-%d-%Y %H:%M:%S" )" | busybox tee -a $LOG;
