#!/system/bin/sh
# Cleaner script
# Copyright (C) 2017 @ala_mo
#=======================================================================#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#=======================================================================#

LOG=/data/intelliboost/cleaner.log

# Loop to reset log values
if [ -f \$LOG ]; then
busybox rm \$LOG;
touch \$LOG;
else
  touch \$LOG;
fi;

#make clean
start at:
$( date +"%m-%d-%Y %H:%M:%S" )


# cleaner
busybox rm -f /data/anr/*.*
busybox rm -f /data/cache/*.*
busybox rm -f /data/log/*.*
busybox rm -f /data/local/tmp/*.*
busybox rm -f /data/mlog/*
busybox rm -f /data/tombstones/*
busybox rm -f /data/backup/pending/*
busybox rm -f /data/system/dropbox/*
chmod 700 /data/system/dropbox
busybox rm -f /data/system/usagestats/*
busybox chmod 700 /data/system/usagestats

export sampling_rate=10000
export up_threshold=80


busybox echo "Successfully cleaned up junk!" | busybox tee -a $LOG;

if [ -e /data/anr/*.* ]; then
  busybox echo "-anr not cleaned" | busybox tee -a $LOG; else
  busybox echo "-anr cleaned" | busybox tee -a $LOG
fi;
if [ -e /data/local/tmp/*.* ]; then
  busybox echo "-local/tmp not cleaned" | busybox tee -a $LOG; else
  busybox echo "-local/tmp cleaned" | busybox tee -a $LOG
fi;
if [ -e /data/cache/*.* ]; then
  busybox echo "-cache not cleaned" | busybox tee -a $LOG; else
  busybox echo "-cache cleaned" | busybox tee -a $LOG
fi;
if [ -e /data/last_log/*.* ]; then
  busybox echo "-log not cleaned" | busybox tee -a $LOG; else
  busybox echo "-log cleaned" | busybox tee -a $LOG
fi;
if [ -e /data/tombstones/*.* ]; then
  busybox echo "-tombstones not cleaned" | busybox tee -a $LOG; else
  busybox echo "-tombstones cleaned" | busybox tee -a $LOG
fi;

busybox echo "Failed? Install busybox!!!!!!!! " | busybox tee -a $LOG
# end
busybox echo "cleaned at$( date +"%m-%d-%Y %H:%M:%S" )" | busybox tee -a $LOG;
