#!/system/bin/sh

if [ -z "$3" ]
then
echo "setprop [key] [value] [file.prop]"
exit 1
fi

exists="$(busybox grep $1= $3)"

busybox mkdir /sdcard/tmp 2> /dev/null

if [ -z "$exists" ]; then
	 busybox echo "$1=$2" >> $3
else 
busybox sed -i "s/${1}=.*/${1}=${2}/g" $3
#mv /sdcard/tmp/build.prop $3
busybox chmod 644 $3
fi;